baseurl      = "localhost"
title        = "Penn Labs Status page"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  isHealthy = true

  dateform        = "Feb 12, 2023"
  dateformShort   = "Jan 2"
  dateformNum     = "2023-02-12"
  dateformNumTime = "2023-02-12 15:04"

  # Subtitle for home
  homeSubtitle = "Penn Labs Status page"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Status page for all labs products (OHQ, Penn Courses, Penn Clubs, Penn Mobile)"
  keywords = "homepage"
  images = [""]

  # Health styles
  healthyLogoCursorColor = "#52de69"
  unhealthyLogoCursorColor = "#fe5186"

[taxonomies]
    category = "status"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "All Products Available"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "status page"
      logoHomeLink = "/"
      logoMark     = ">"
      
      # Set true to remove the logo cursor entirely.
      # logoCursorDisabled = false
      # Set to a valid CSS time value to change the animation duration, "0s" to disable.
      # logoCursorAnimate  = "2s"
      # Append the current url pathname to logoText 
      # logoCursorPathname = true

  # And you can even create generic menu
  [[menu.main]]
    identifier = "Availability Details"
    name       = "Availability Details"
    url        = "/products"



    